# Generated by Django 2.2 on 2019-04-14 22:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.TextField()),
                ('tweet_status', models.IntegerField(default=1)),
                ('tweet_type', models.IntegerField(default=1)),
                ('like_count', models.IntegerField(default=0)),
                ('reply_count', models.IntegerField(default=0)),
                ('retweet_count', models.IntegerField(default=0)),
                ('is_retweeted', models.BooleanField(default=False)),
                ('original_tweet_id', models.IntegerField(blank=True, null=True)),
                ('media_id', models.IntegerField(blank=True, null=True)),
                ('tweet_created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowerRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.IntegerField()),
                ('follow_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=10, unique=True)),
                ('content', models.TextField()),
                ('content_format', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)])),
                ('protected', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
