# Generated by Django 2.2 on 2019-04-15 00:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followerrelations',
            unique_together={('user_id', 'follower_id')},
        ),
        migrations.DeleteModel(
            name='Bin',
        ),
    ]
